files:
  - source: /source/**/*.json
    translation: /translations/**/%locale%/%original_file_name%
  - source: /source/**/*.json
    translation: /translations/**/%two_letters_code%/%original_file_name%
